### ISSUE TITLE
compatibility with python3

### ISSUE THREAD

**Issue by lincolnBush** [rmcantin/bayesopt#14]
According to the python code, it seems to be compatible with python 3 but when I tried to install it with python 3.5, and import bayesopt, the error occurred:

ImportError: dynamic module does not define module export function(PyInit_bayesopt)

Any idea to solve this, many thanks.

**Comment by rmcantin** [comment]
Python 3.x is not officially supported, but it should work just fine from Cython. Maybe the generated python/bayesopt.cpp is too old. 

Try generating again the Cython code with the latest Cython version. The instructions are here: https://rmcantin.bitbucket.io/html/contriblib.html#modcython

**Comment by rmcantin** [comment]
Fixed with PR #11
