### ISSUE TITLE
Use BayesOPT to optimize categorical variables

### ISSUE THREAD

**Issue by csjtx1021** [rmcantin/bayesopt#15]
Hey Ruben,
Sorry to disturb you. I have a question about categorical variables. My inputs are 8 binary variables (0/1). 
Here is the running status and the results.

[bayesopt1.txt](https://github.com/rmcantin/bayesopt/files/1018470/bayesopt1.txt)
[log1.txt](https://github.com/rmcantin/bayesopt/files/1018467/log1.txt)
[bayesopt2.txt](https://github.com/rmcantin/bayesopt/files/1018471/bayesopt2.txt)
[log2.txt](https://github.com/rmcantin/bayesopt/files/1018468/log2.txt)

When "mParameters.noise" is small e.g. 1e-10, there is a error in log1.txt. But when "mParameters.noise" is equal to 1.0, there is not any error. Why did this happen ? This question has been bothering me for a long time.  Have a favor. 

Thanks a lot.

Cui

**Comment by rmcantin** [comment]
Closed after no feedback
