### ISSUE TITLE
About mSigma (variance) in gaussian_process.cpp

### ISSUE THREAD

**Issue by timberjack** [rmcantin/bayesopt#17]
Dear Authors,

I am studying about gaussian process in LCB (Lower Confidence Bounds) evaluation. I take _bo_branin.cpp_ as an example. I found variance is constantly lower than 1, which could be much smaller than mean value even in the early training step (for example, a gaussian model with only 2 samples trained. I tried my own example with mean value at around 170, but 0.2 variance with only 2 samples trained, where (170+-0.2) cannot contain the real value). 

Through studying _gaussian_process.cpp_, I found that _mSigma_ hugely decides the value of covariance. _mSigma_ is set or gotten from function _setHyperParameters_ and _getHyperParameters_ in _kernelRegressor.hpp_, and is updated through _kOptimizer_ in _posterior_empirical.cpp_. An initial 2-dimension points, mean and variance is combined into a 4-dimension vector to insert to kOptimizer. However, I doubt mean and variance is not calculated correctly as they are probably treated as same as the coordinates of 2-dimension points in _kernelRegressor.hpp_.

Could you help check about the calculation of variance? I feel interested into studying more.

Thanks,
Xianan

**Comment by rmcantin** [comment]
The variance is computed correctly. For certain models (not in all of them), the variance is estimated as a hyperparameter of the GP, like the kernel hyperparameters.
