### ISSUE TITLE
Build error on Ubuntu 17.04

### ISSUE THREAD

**Issue by usptact** [rmcantin/bayesopt#18]
I cloned the repo, created a "build" directory inside and ran "cmake .." from within that directory. Finally, I attempted to run "make". The compilation seems to be going well till this point:

`[ 71%] Building CXX object CMakeFiles/bayesopt.dir/utils/fileparser.cpp.o
/home/vlad/tools/bayesopt/utils/fileparser.cpp: In member function ‘bool bayesopt::utils::FileParser::fileExists()’:
/home/vlad/tools/bayesopt/utils/fileparser.cpp:88:23: error: cannot convert ‘std::ifstream {aka std::basic_ifstream<char>}’ to ‘bool’ in initialization
         bool result = ifile;
                       ^~~~~
CMakeFiles/bayesopt.dir/build.make:734: recipe for target 'CMakeFiles/bayesopt.dir/utils/fileparser.cpp.o' failed
make[2]: *** [CMakeFiles/bayesopt.dir/utils/fileparser.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/bayesopt.dir/all' failed
make[1]: *** [CMakeFiles/bayesopt.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by usptact** [comment]
It turns out that gcc 6.3.0 does not work; The alternative gcc 5.4.1 works just fine. All you need is to install/update alternatives in Ubuntu.

**Comment by zmiimz** [comment]
imho, it is better to fix the code https://stackoverflow.com/questions/38659115/make-fails-with-error-cannot-convert-stdistream-aka-stdbasic-istreamchar
utils/fileparser.cpp
88        bool result =  static_cast<bool>(ifile);

**Comment by usptact** [comment]
@zmiimz Thanks a lot for pointing this out! I created a merge request #19

**Comment by rmcantin** [comment]
Thanks. This should be fixed in commit 1326549b68f27801b79984ca227f4183d984107d
