### ISSUE TITLE
Parallelization for matlab wrapper

### ISSUE THREAD

**Issue by san-bil** [rmcantin/bayesopt#2]
Is there any way to parallelize the function evaluations for the matlab implementation of bayesoptcont()?

If not for the actual optimization (due to the sequential dependency), then at least for the initial function evaluations (set by n_init_samples)? If I can have 20 of those initial samples running simultaneously using HTcondor, it's pretty wasteful to do them serially.

**Comment by rmcantin** [comment]
We are working on a parallelized version of BayesOpt, but it is complicated as Bayesian optimization is inherently sequential by definition.

Meanwhile, the next release will include a save  and restore mechanism which can be use to preload initial samples computed separately.

**Comment by san-bil** [comment]
Yeah of course, I'm not sure how you'd actually parallelize the optimization, just that initial sampling of the parameter space. The preloading feature would be a handy way of doing it.

**Comment by PiranjaF** [comment]
Any thoughts on when the next version is released? Looking very much forward to this added functionality!
