### ISSUE TITLE
Why it doesn't converge to the right value

### ISSUE THREAD

**Issue by zhaozhongch** [rmcantin/bayesopt#20]
Hi 
Thanks for viewing the question.
I run the bayes optimization for my problem and get the data below.
The first column is output y and second column is x
317.402,-0.278159//10 sample, 70 iteration
485.787,-0.325544
489.675,-0.256076
577.022,-0.244675
339.859,-0.310618
289.268,-0.282267
603.213,-0.241337
383.85,-0.314427
428.921,-0.265534
264.013,-0.296477// sample ends
296.115,-0.2817
297.359,-0.2817
296.15,-0.2817
295.788,-0.2817
296.233,-0.2817
296.172,-0.2817
295.955,-0.2817
295.969,-0.2817
295.711,-0.2817
295.864,-0.2817
296.037,-0.2817
296.08,-0.2817
.....

As you can see the value of x converge to -0.2817, however you can see when x = 0.296477, the output is smaller(264). In fact as I run my function by adding 0.001 to x from -0.33 to 0.23 I  found when x is about -0.2917 y will output the smallest value.
In my problem the output is not deterministic because an algorithm called RANSAC but it will be near a certain value as you can see when x = -0.2817 y has different values but won't change too much. So what might be the problem? Why the bayesopt cannot find the minimum?
I use the default parameter.

**Comment by rmcantin** [comment]
The default parameters are for deterministic functions.
