### ISSUE TITLE
noise effect

### ISSUE THREAD

**Issue by zhaozhongch** [rmcantin/bayesopt#21]
About noise the instruction says: Too much noise results in slow convergence while not enough noise might result in not converging at all
Why is that?

**Comment by rmcantin** [comment]
We use a GP for modeling the function to optimize. If you asume 0 noise, you are considering the GP is a perfect model, but of course, the GP cannot model any function. If you asume a large noise, you are considering that the GP is a bad model, thus it does not help to converge.
