### ISSUE TITLE
[Request] Add a CITATION.cff file

### ISSUE THREAD

**Issue by scrungus** [rmcantin/bayesopt#29]
A CITATION.cff file should be added to this repository so that it can be correctly cited in academic papers. 

Thanks

**Comment by rmcantin** [comment]
Please, never cite the repository. As stated in the README, you should cite the paper instead:

- Ruben Martinez-Cantin, BayesOpt: A Bayesian Optimization Library for Nonlinear Optimization, Experimental Design and Bandits. Journal of Machine Learning Research, 15(Nov):3735--3739, 2014.
