### ISSUE TITLE
x, f input size to bayes_optimization_disc

### ISSUE THREAD

**Issue by edz504** [rmcantin/bayesopt#8]
Hey Ruben,

Thanks for this great package.  I'm looking to understand why in your `bo_disc.cpp` example,[ the input x and fmin](https://github.com/rmcantin/bayesopt/blob/master/examples/bo_disc.cpp#L128) that are modified to contain the optimizer and the optimal value are initialized with size 128.  I notice this value appear in [many other places](https://github.com/rmcantin/bayesopt/search?utf8=%E2%9C%93&q=128), so I was hoping you could help me see why.

Thanks!

**Comment by rmcantin** [comment]
Standard size value.
